version: 0.2

phases:
   pre_build:
      commands:
#          - n latest
         - rm -rf node_modules
         - rm -f package-lock.json
         - echo REACT_APP_ENV=$REACT_APP_ENV | tee -a .env
         - echo REACT_APP_API_URL_STAGE=$REACT_APP_API_URL_STAGE | tee -a .env
         - cat .env
         - echo Installing source NPM dependencies...
         - npm install
   build:
      commands:
         - echo Build started on `date`...
         - npm run build
   post_build:
      commands:
         - echo Build completed on `date`
         - ls build
artifacts:
   files:
      - "**/*"
